[2024-01-07 18:49:38,679] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2024-01-07T18:49:29.134823+00:00 [queued]>
[2024-01-07 18:49:38,697] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2024-01-07T18:49:29.134823+00:00 [queued]>
[2024-01-07 18:49:38,697] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-01-07 18:49:38,697] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-01-07 18:49:38,697] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-01-07 18:49:38,726] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): training_model> on 2024-01-07 18:49:29.134823+00:00
[2024-01-07 18:49:38,736] {standard_task_runner.py:52} INFO - Started process 7220 to run task
[2024-01-07 18:49:38,739] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'training_model', 'manual__2024-01-07T18:49:29.134823+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_training_pipeline/.ipynb_checkpoints/lead_scoring_training_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmpm98cvb7v', '--error-file', '/tmp/tmpgm121pzy']
[2024-01-07 18:49:38,739] {standard_task_runner.py:80} INFO - Job 37: Subtask training_model
[2024-01-07 18:49:38,820] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2024-01-07T18:49:29.134823+00:00 [running]> on host a3830b6d5f93
[2024-01-07 18:49:38,914] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=training_model
AIRFLOW_CTX_EXECUTION_DATE=2024-01-07T18:49:29.134823+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-07T18:49:29.134823+00:00
[2024-01-07 18:49:38,915] {logging_mixin.py:115} INFO - unable to open database file
[2024-01-07 18:49:38,925] {logging_mixin.py:115} INFO - Loading 'features' table
[2024-01-07 18:49:42,605] {logging_mixin.py:115} INFO - Loading 'target' table
[2024-01-07 18:49:42,843] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dags/lead_scoring_training_pipeline/utils.py", line 151, in get_trained_model
    with contextlib.suppress(Exception):
NameError: name 'contextlib' is not defined
[2024-01-07 18:49:42,856] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_scoring_training_pipeline, task_id=training_model, execution_date=20240107T184929, start_date=20240107T184938, end_date=20240107T184942
[2024-01-07 18:49:42,882] {standard_task_runner.py:92} ERROR - Failed to execute job 37 for task training_model (name 'contextlib' is not defined; 7220)
[2024-01-07 18:49:42,925] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-07 18:49:42,969] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
