[2024-01-07 18:32:25,745] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables manual__2024-01-07T18:32:11.845395+00:00 [queued]>
[2024-01-07 18:32:25,761] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables manual__2024-01-07T18:32:11.845395+00:00 [queued]>
[2024-01-07 18:32:25,761] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-01-07 18:32:25,761] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2024-01-07 18:32:25,761] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-01-07 18:32:25,790] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): encoding_categorical_variables> on 2024-01-07 18:32:11.845395+00:00
[2024-01-07 18:32:25,800] {standard_task_runner.py:52} INFO - Started process 5401 to run task
[2024-01-07 18:32:25,805] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'encoding_categorical_variables', 'manual__2024-01-07T18:32:11.845395+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_training_pipeline/lead_scoring_training_pipeline.py', '--cfg-path', '/tmp/tmpc1atsalb', '--error-file', '/tmp/tmpmsh90kfw']
[2024-01-07 18:32:25,806] {standard_task_runner.py:80} INFO - Job 32: Subtask encoding_categorical_variables
[2024-01-07 18:32:25,895] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.encoding_categorical_variables manual__2024-01-07T18:32:11.845395+00:00 [running]> on host a3830b6d5f93
[2024-01-07 18:32:25,982] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=encoding_categorical_variables
AIRFLOW_CTX_EXECUTION_DATE=2024-01-07T18:32:11.845395+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-07T18:32:11.845395+00:00
[2024-01-07 18:32:25,990] {logging_mixin.py:115} INFO - Loading model_input table
[2024-01-07 18:32:25,991] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/sql.py", line 2020, in execute
    cur.execute(*args, **kwargs)
sqlite3.OperationalError: no such table: model_input

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/dags/lead_scoring_training_pipeline/utils.py", line 65, in encode_features
    df = pd.read_sql("select * from model_input", cnx)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/sql.py", line 566, in read_sql
    return pandas_sql.read_query(
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/sql.py", line 2080, in read_query
    cursor = self.execute(*args)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/sql.py", line 2032, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'select * from model_input': no such table: model_input
[2024-01-07 18:32:26,004] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Lead_scoring_training_pipeline, task_id=encoding_categorical_variables, execution_date=20240107T183211, start_date=20240107T183225, end_date=20240107T183226
[2024-01-07 18:32:26,030] {standard_task_runner.py:92} ERROR - Failed to execute job 32 for task encoding_categorical_variables (Execution failed on sql 'select * from model_input': no such table: model_input; 5401)
[2024-01-07 18:32:26,055] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-07 18:32:26,128] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
